name: Validate Server Website

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          registry-url: https://npm.pkg.github.com
          scope: "@reuben-williams"

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}

      - name: Test
        run: npm test

      - name: Lint
        run: npm run lint

      - name: Build server application
        run: npm run build
        env:
          NEXT_PUBLIC_SITE_URL: http://localhost:3000
